added curl to ensure the website still works

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -131,3 +131,15 @@ jobs:
 
       - name: Restart services
         run: ssh production docker stack deploy --compose-file /opt/ubyssey.ca/docker-compose.yml ubyssey
+
+      - name: Check health of the application
+        run: |
+          MAX_ATTEMPTS=15
+          for ((i=1; i<=MAX_ATTEMPTS; i++)); do
+            if ssh production curl -f -s https://ubyssey.ca/health/ >/dev/null 2>&1; then
+              exit 0
+            fi
+            sleep 10
+          done
+          echo "Health check failed"
+          exit 1
